Algoritmo "escrever mensagem"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Escrever Mensagem
// Autor(a)    : Felipe Barnabé
// Data atual  : 12/07/2024
Var
// Seção de Declarações das variáveis 
  msg: caractere
  msg_teste: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  msg <- "Ola, Mundo!")
  Escreval(msg)
  msg_teste <- "Teste mensagem!")
  Escreval(msg_teste)

Fimalgoritmo