Algoritmo "MeuNome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Aguarda entrada de um nome e exibe uma boas vindas
// Autor(a)    : Felipe Barnabé
// Data atual  : 12/07/2024
Var
// Seção de Declarações das variáveis 
  Nome: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  Escreva ("Digite seu nome: ")
  Leia (Nome)
  Escreva ("Muito prazer " , nome)

Fimalgoritmo