Algoritmo "temperatura"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Felipe Barnabé
// Data atual  : 15/07/2024
Var
// Seção de Declarações das variáveis 
   F, C: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Qual é a temperatura aqui?: ")
   Leia(F)
   C <- (F - 32) / 1.8
   Escreva("No Brasil estaria: ", C)

Fimalgoritmo